defaults: &defaults
  working_directory: ~/app
  docker:
    - image: softinstigate/serverless

version: 2
jobs:

  deploy:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Deploy
          command: yarn deploy:prod

workflows:
  version: 2

  deployment:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
