defaults: &defaults
  working_directory: ~/app
  docker:
    - image: node:8.10

version: 2
jobs:

  deploy:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Get Env File
          command: aws s3 cp s3://rogers-config/env-var/archeravenueBackend/env.json ./ --region $AWS_REGION
      - run:
          name: Deploy
          command: yarn deploy:prod

workflows:
  version: 2

  deployment:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
