defaults: &defaults
  working_directory: ~/app
  docker:
    - image: gradyrogers/awscli

version: 2
jobs: 

  deploy:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Get Env File
          command: aws s3 cp s3://rogers-config/env-vars/archeravenueBackend/env.json ./ --region $AWS_REGION
      - run:
          name: Deploy
          command: npm run deploy:dev

workflows:
  version: 2

  deployment:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
